'use strict';
const assert=require('assert');
const registry=require('./assets/js/print-sections.js'); registry.clearRegistry();
const section=require('./assets/js/print/sections/property-summary.js');
const source=Object.freeze({propertySummary:{available:true,address:'123 <Main> St, Fremont, CA 94539',yearBuilt:1998,squareFeet:2100,stories:2,constructionType:'Frame',foundationType:'Slab',roof:'Composition',coverage:{replacementCost:850000,deductible:5000,currentCarrier:'Farmers'},riskHighlights:['Pool <review>','Older roof review']}});
const out=section.render(source);
assert.ok(out.html.includes('cf-property-overview'));
assert.ok(out.html.includes('cf-property-main-grid'));
assert.ok(out.html.includes('cf-property-coverage-card'));
assert.ok(out.html.includes('cf-property-risk-list'));
assert.ok(out.html.includes('cf-property-footer'));
assert.ok(out.html.includes('CoverageFit · Confidential consultation material'));
assert.ok(out.html.includes('$850,000'));
assert.ok(out.html.includes('2,100 sq. ft.'));
assert.ok(out.html.includes('&lt;Main&gt;'));
assert.ok(!out.html.includes('<Main>'));
assert.ok(out.html.includes('Pool &lt;review&gt;'));
assert.ok(Object.isFrozen(out.model));
const empty=section.render({propertySummary:{available:true,address:'1 Test St'}});
assert.ok(empty.html.includes('cf-property-empty'));
assert.ok(empty.html.includes('No specific risk highlights captured'));
const renderer=require('./assets/js/print-renderers.js');
assert.ok(String(renderer.__css || '').length >= 0 || renderer);
console.log(JSON.stringify({suite:'P1.2.3 Professional Property Summary Layout',passed:15,failed:0},null,2));
